config/routes.rb
Psycho::Application.routes.draw do
  resources :days
  root :to => redirect("/days")

  

end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date, :act1, :act2, :act3, :morning, :sport, :meditation, :mood)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :act1 %><br>
    <%= f.text_area :act1 %>
  </div>
  <div class="field">
    <%= f.label :act2 %><br>
    <%= f.text_area :act2 %>
  </div>
  <div class="field">
    <%= f.label :act3 %><br>
    <%= f.text_area :act3 %>
  </div>
  <div class="field">
    <%= f.label :morning %><br>
    <%= f.check_box :morning %>
  </div>
  <div class="field">
    <%= f.label :sport %><br>
    <%= f.check_box :sport %>
  </div>
  <div class="field">
    <%= f.label :meditation %><br>
    <%= f.check_box :meditation %>
  </div>
  <div class="field">
    <%= f.label :mood %><br>
    <%= f.text_field :mood %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Act1</th>
      <th>Act2</th>
      <th>Act3</th>
      <th>Morning</th>
      <th>Sport</th>
      <th>Meditation</th>
      <th>Mood</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.date %></td>
        <td><%= day.act1 %></td>
        <td><%= day.act2 %></td>
        <td><%= day.act3 %></td>
        <td><%= day.morning %></td>
        <td><%= day.sport %></td>
        <td><%= day.meditation %></td>
        <td><%= day.mood %></td>
        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @day.date %>
</p>

<p>
  <strong>Act1:</strong>
  <%= @day.act1 %>
</p>

<p>
  <strong>Act2:</strong>
  <%= @day.act2 %>
</p>

<p>
  <strong>Act3:</strong>
  <%= @day.act3 %>
</p>

<p>
  <strong>Morning:</strong>
  <%= @day.morning %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @day.sport %>
</p>

<p>
  <strong>Meditation:</strong>
  <%= @day.meditation %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @day.mood %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Psycho</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">The Idea app</a>
	    </div>
	    <div class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="/ideas">Ideas</a></li>
	      </ul>
	    </div>
	  </div>
	</nav>


	<div class="container">
	  <%= yield %>
	</div>


	<footer>
	  <div class="container">
	    Rails Girls 2014
	  </div>
	</footer>
	<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>